// Generated by Analysis Studio v0.7. Review before production use.
#include <stdio.h>
#include <string>
#include <vector>
#include <map>
#include <filesystem>

#include "TFile.h"
#include "Loader.h"

int main(int argc, char* argv[]) {
    // Loader chain 1: Tau tree
    // Tau tree
    Loader loader("tau_lfv");

    // Signal input
    if (argc <= 1) { fprintf(stderr, "Missing input directory argument 1\n"); return 2; }
    loader.Load(argv[1], ".root", "SIGNAL");

    // Preselection
    loader.Cut("(-0.3 < deltaE) && (deltaE < 0.15)");
    loader.PrintInformation("Energy window");
    loader.Cut("(1.71 < M) && (M < 1.82)");
    loader.PrintInformation("Mass window");

    // Selected distributions
    if (!std::filesystem::path("plots/M.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/M.png").parent_path());
    loader.DrawTH1D("M", ";M [GeV];Events", 50, 1.5, 1.9, "plots/M.png");
    if (!std::filesystem::path("plots/deltaE.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/deltaE.png").parent_path());
    loader.DrawTH1D("deltaE", ";deltaE [GeV];Events", 60, -0.3, 0.15, "plots/deltaE.png");

    // Mass fit
    {
    loader.DefineObservable("studio_2dd105feeca1_x", "M", 1.71, 1.82);
    loader.SetRange("studio_2dd105feeca1_x", "studio_2dd105feeca1_range", 1.77, 1.785);
    loader.DefineAndFillDataSet("studio_2dd105feeca1_data", {"studio_2dd105feeca1_x"}, {"M"});
    loader.DefineFitParameter("studio_2dd105feeca1_p0_mean", "mean", 1.777, 1.7, 1.85);
    loader.DefineFitParameter("studio_2dd105feeca1_p1_sigma_left", "sigma_left", 0.005, 1e-05, 0.1);
    loader.DefineFitParameter("studio_2dd105feeca1_p2_sigma_right", "sigma_right", 0.005, 1e-05, 0.1);
    loader.DefineModel("studio_2dd105feeca1_pdf", "RooBifurGauss", {"studio_2dd105feeca1_x"}, {"studio_2dd105feeca1_p0_mean", "studio_2dd105feeca1_p1_sigma_left", "studio_2dd105feeca1_p2_sigma_right"});
    FitOptions fit_options;
    fit_options.strategy = 1;
    fit_options.SumW2Error = true;
    fit_options.range = "studio_2dd105feeca1_range";
    loader.Fit("studio_2dd105feeca1_fit", "studio_2dd105feeca1_data", "studio_2dd105feeca1_pdf", fit_options);
    if (!std::filesystem::path("plots/M_fit.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/M_fit.png").parent_path());
    FitPlotOptions plot_options;
    plot_options.bins = 100;
    plot_options.sumW2Error = true;
    plot_options.showFitparam = true;
    loader.PlotFit("studio_2dd105feeca1_fit", "studio_2dd105feeca1_x", "plots/M_fit.png", plot_options);
    if (!std::filesystem::path("results/M_parameters.root").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("results/M_parameters.root").parent_path());
    loader.ExportFitResult("results/M_parameters.root", {"studio_2dd105feeca1_fit"});
    }

    // Energy fit
    {
    loader.DefineObservable("studio_660c6dca6d4c_x", "deltaE", -0.3, 0.15);
    loader.SetRange("studio_660c6dca6d4c_x", "studio_660c6dca6d4c_range", -0.02, 0.02);
    loader.DefineAndFillDataSet("studio_660c6dca6d4c_data", {"studio_660c6dca6d4c_x"}, {"deltaE"});
    loader.DefineFitParameter("studio_660c6dca6d4c_p0_mean", "mean", 0.0, -0.1, 0.1);
    loader.DefineFitParameter("studio_660c6dca6d4c_p1_sigma_left", "sigma_left", 0.014, 0.008, 0.02);
    loader.DefineFitParameter("studio_660c6dca6d4c_p2_sigma_right", "sigma_right", 0.014, 0.008, 0.02);
    loader.DefineModel("studio_660c6dca6d4c_pdf", "RooBifurGauss", {"studio_660c6dca6d4c_x"}, {"studio_660c6dca6d4c_p0_mean", "studio_660c6dca6d4c_p1_sigma_left", "studio_660c6dca6d4c_p2_sigma_right"});
    FitOptions fit_options;
    fit_options.strategy = 1;
    fit_options.SumW2Error = true;
    fit_options.range = "studio_660c6dca6d4c_range";
    loader.Fit("studio_660c6dca6d4c_fit", "studio_660c6dca6d4c_data", "studio_660c6dca6d4c_pdf", fit_options);
    if (!std::filesystem::path("plots/deltaE_fit.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/deltaE_fit.png").parent_path());
    FitPlotOptions plot_options;
    plot_options.bins = 100;
    plot_options.sumW2Error = true;
    plot_options.showFitparam = true;
    loader.PlotFit("studio_660c6dca6d4c_fit", "studio_660c6dca6d4c_x", "plots/deltaE_fit.png", plot_options);
    if (!std::filesystem::path("results/deltaE_parameters.root").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("results/deltaE_parameters.root").parent_path());
    loader.ExportFitResult("results/deltaE_parameters.root", {"studio_660c6dca6d4c_fit"});
    if (!std::filesystem::path("results/workspace.root").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("results/workspace.root").parent_path());
    loader.SaveWorkspace("results/workspace.root");
    }

    // Run analysis
    loader.end();

    return 0;
}
