// Generated by Analysis Studio v0.7. Review before production use.
#include <stdio.h>
#include <string>
#include <vector>
#include <map>
#include <filesystem>
#include <stdexcept>

#include "TFile.h"
#include "Loader.h"



int main(int argc, char* argv[]) {
    // Loader chain 1: Loader Declaration
    // Loader Declaration
    Loader loader("tau_lfv");

    // Samples
    loader.Load("Ntuple/SIGNAL/test", ".root", "SIGNAL");
    loader.Load("Ntuple/BACKGROUND/test", ".root", "BACKGROUND");

    // Sample Roles
    loader.SetMC({"SIGNAL", "BACKGROUND"});
    loader.SetData({});
    loader.SetSignal({"SIGNAL"});
    loader.SetBackground({"BACKGROUND"});

    // Apply FastBDT
    loader.FastBDTApplication({"M", "deltaE"}, "models/tau.weightfile", "BDT_output");

    // Variable Optimization
    if (!std::filesystem::path("results/test_auc.txt").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("results/test_auc.txt").parent_path());
    loader.CalculateAUC("BDT_output", 0.0, 1.0, "results/test_auc.txt", "w");

    // Variable Optimization
    if (!std::filesystem::path("plots/test_punzi.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/test_punzi.png").parent_path());
    loader.DrawPunziFOM("BDT_output", 0.0, 1.0, 100, 1000.0, 1.28, 1, "plots/test_punzi.png");

    // End
    loader.end();

    return 0;
}
