// Generated by Analysis Studio v0.7. Review before production use.
#include <stdio.h>
#include <string>
#include <vector>
#include <map>
#include <filesystem>
#include <stdexcept>

#include "TFile.h"
#include "Loader.h"



int main(int argc, char* argv[]) {
    // Loader chain 1: Loader Declaration
    // Loader Declaration
    Loader loader("tau_lfv");

    // Samples
    loader.Load("Ntuple/SIGNAL/input", ".root", "SIGNAL");
    loader.Load("Ntuple/BACKGROUND/input", ".root", "BACKGROUND");

    // Sample Roles
    loader.SetMC({"SIGNAL", "BACKGROUND"});
    loader.SetData({});
    loader.SetSignal({"SIGNAL"});
    loader.SetBackground({"BACKGROUND"});

    // Ranked Variables
    loader.ConditionalPairDefineNewVariable({{"extraInfo__boOneMuon_p__bc", "extraInfo__boOneMuon_muonID__bc"}, {"extraInfo__boTwoMuon_p__bc", "extraInfo__boTwoMuon_muonID__bc"}, {"extraInfo__boThreeMuon_p__bc", "extraInfo__boThreeMuon_muonID__bc"}}, 0, "first_muon_muonID");
    loader.ConditionalPairDefineNewVariable({{"extraInfo__boOneMuon_p__bc", "extraInfo__boOneMuon_muonID__bc"}, {"extraInfo__boTwoMuon_p__bc", "extraInfo__boTwoMuon_muonID__bc"}, {"extraInfo__boThreeMuon_p__bc", "extraInfo__boThreeMuon_muonID__bc"}}, 1, "second_muon_muonID");
    loader.ConditionalPairDefineNewVariable({{"extraInfo__boOneMuon_p__bc", "extraInfo__boOneMuon_muonID__bc"}, {"extraInfo__boTwoMuon_p__bc", "extraInfo__boTwoMuon_muonID__bc"}, {"extraInfo__boThreeMuon_p__bc", "extraInfo__boThreeMuon_muonID__bc"}}, 2, "third_muon_muonID");

    // Variables
    loader.GetAverage({"extraInfo__boOneMuon_cosToThrustOfEvent__bc", "extraInfo__boTwoMuon_cosToThrustOfEvent__bc", "extraInfo__boThreeMuon_cosToThrustOfEvent__bc"}, "avg_cosToThrust");
    loader.GetStdDev({"extraInfo__boOneMuon_cosToThrustOfEvent__bc", "extraInfo__boTwoMuon_cosToThrustOfEvent__bc", "extraInfo__boThreeMuon_cosToThrustOfEvent__bc"}, "stddev_cosToThrust");
    loader.GetDiff({"extraInfo__boOneMuon_cosToThrustOfEvent__bc", "extraInfo__boTwoMuon_cosToThrustOfEvent__bc", "extraInfo__boThreeMuon_cosToThrustOfEvent__bc"}, 0, "diff_cosToThrust");

    // Cut Flow
    loader.Cut("(1.71 < M) && (M < 1.82)");
    loader.PrintInformation("Mass window");
    loader.Cut("(-0.3 < deltaE) && (deltaE < 0.15)");
    loader.PrintInformation("Energy window");

    // Candidate Selection
    loader.RandomBCS({"__experiment__", "__run__", "__event__", "__production__", "__ncandidates__"});

    // Candidate Selection
    loader.IsBCSValid({"__experiment__", "__run__", "__event__", "__production__", "__ncandidates__"});

    // Stack Plot Set
    if (!std::filesystem::path("plots/M.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/M.png").parent_path());
    loader.DrawStack("M", ";M [GeV];Events", 50, 1.5, 1.9, "plots/M.png", false, false);

    // 2D Plot Set
    if (!std::filesystem::path("plots/M_deltaE.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/M_deltaE.png").parent_path());
    loader.DrawTH2D("M", "deltaE", ";M [GeV];deltaE [GeV]", 50, 1.5, 1.9, 50, -0.3, 0.15, "plots/M_deltaE.png", "COLZ");

    // Profile Fit
    loader.DefineAndFillProfile("studio_b9a8de7aac6e_profile", ";deltaE;M", 100, -0.3, 0.15, 1.71, 1.82, "deltaE", "M");
    loader.DefineTF1("studio_b9a8de7aac6e_model", "[0] + [1]*x", -0.3, 0.15, {{"intercept", 1.777, 1.7, 1.85, false}, {"slope", 0.0, -1.0, 1.0, false}});
    loader.Fit("studio_b9a8de7aac6e_fit", "studio_b9a8de7aac6e_profile", "studio_b9a8de7aac6e_model");
    if (!std::filesystem::path("plots/profile_fit.png").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("plots/profile_fit.png").parent_path());
    loader.PlotFit("studio_b9a8de7aac6e_fit", "", "plots/profile_fit.png");
    if (!std::filesystem::path("results/profile_parameters.root").parent_path().empty()) std::filesystem::create_directories(std::filesystem::path("results/profile_parameters.root").parent_path());
    loader.ExportFitResult("results/profile_parameters.root", {"studio_b9a8de7aac6e_fit"});

    // Event Split
    loader.RandomEventSelection(2, 0, {"__experiment__", "__run__", "__event__", "__production__", "__ncandidates__"});

    // ROOT Output
    if (!std::filesystem::path("selected/partition_0").empty()) std::filesystem::create_directories(std::filesystem::path("selected/partition_0"));
    loader.PrintSeparateRootFile("selected/partition_0", "", "");

    // End
    loader.end();

    return 0;
}
