// Generated by Analysis Studio v0.7. Review before production use.
#include <stdio.h>
#include <string>
#include <vector>
#include <map>
#include <filesystem>
#include <stdexcept>

#include "TFile.h"
#include "Loader.h"



int main(int argc, char* argv[]) {
    // Loader chain 1: Loader Declaration
    // Loader Declaration
    Loader loader("tau_lfv");

    // Samples
    loader.Load("Ntuple/SIGNAL/train", ".root", "SIGNAL");
    loader.Load("Ntuple/BACKGROUND/train", ".root", "BACKGROUND");

    // Sample Roles
    loader.SetMC({"SIGNAL", "BACKGROUND"});
    loader.SetData({});
    loader.SetSignal({"SIGNAL"});
    loader.SetBackground({"BACKGROUND"});

    // Train FastBDT
    if (!std::filesystem::path("models").empty()) std::filesystem::create_directories(std::filesystem::path("models"));
    loader.FastBDTTrain({"M", "deltaE"}, "", "", {{"NTrees", 100.0}, {"Depth", 3.0}, {"Shrinkage", 0.1}, {"Subsample", 0.5}, {"Binning", 8.0}}, true, "models", "tau.weightfile");

    // End
    loader.end();

    return 0;
}
